cmake_minimum_required(VERSION 3.20.0)

# set(cond_var_1 TRUE)
# set(cond_var_1 "ON")
# set(cond_var_1 "Y")
# set(cond_var_1 "TRUE")
set(cond_var_1 "2")

# set(cond_var_2 FALSE)
# set(cond_var_2 "OFF")
# set(cond_var_2 "N")
# set(cond_var_2 "NO")
# set(cond_var_2 "FALSE")
# set(cond_var_2 "IGNORED")
# set(cond_var_2 "NOTFOUND")
# set(cond_var_2 "")
# set(cond_var_2 "name-NOTFOUND")
# set(cond_var_2 "0")

if(${cond_var_1})
  message("cond_var_1 is true")
else()
  message("cond_var_1 is false")
endif()

if(${cond_var_2})
  message("cond_var_2 is true")
else()
  message("cond_var_2 is false")
endif()

set(FOO "BAR")
if (FOO)
  message("FOO is true")
else()
  message("FOO is false")
endif()

if(DEFINED FOO)
  message("FOO defined")
endif()

if(DEFINED BAR)
  message("BAR define")
endif()

set(comp_var_1 20)
set(comp_var_2 "21 GB")
if (comp_var_1 LESS comp_var_2)
  message("LESS")
elseif(comp_var_1 EQUAL comp_var_2)
  message("EQUAL")
elseif(comp_var_1 LESS_EQUAL comp_var_2)
  message("LESS_EQUAL")
elseif(comp_var_1 GREATER comp_var_2)
  message("GREATER")
elseif(comp_var_1 GREATER_EQUAL comp_var_2)
  message("GREATEE_EQUAL")
endif()

if (1.3.4 VERSION_LESS_EQUAL 1.4)
  message("VERSION_LESS_EQUAL")
endif()

set(B "A")
if ("A" STREQUAL B)
  message("STREQUAL")
endif()

if (EXISTS "build")
  message("build exist")
endif()
